[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
# Some warnings should be omitted
ignored_warnings_from = [
    # Warning (3628): This contract has a payable fallback function, but no receive ether function
    "src/MirrorProxy.sol",
]
# Enable new EVM codegen
via_ir = true

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

